"""Repository interfaces (ports in hexagonal-architecture terms).

Consumers (services/handlers) know only these protocols; concrete SQL
lives in the implementations registered in the container.
"""
from typing import Any, Dict, Optional, Protocol

from ..models.account import Account, PlayerData


class AccountRepository(Protocol):
    def create(self, username: str, password_hash: str, salt: str) -> Account: ...
    def find_by_username(self, username: str) -> Optional[tuple]: ...
    def find_by_id(self, account_id: int) -> Optional[Account]: ...
    def create_token(self, account_id: int, token: str) -> None: ...
    def account_id_for_token(self, token: str) -> Optional[int]: ...


class PlayerDataRepository(Protocol):
    def load(self, account_id: int) -> PlayerData: ...
    def save(self, player: PlayerData) -> None: ...
